"""Secrets sidecar (Phase 13.6).

Cloud LLM API keys and similar credentials live in ``secrets.yaml``,
a sibling of ``config.yaml`` with ``chmod 600`` so only the
local-process owner can read it. ``config.yaml`` references each
secret by name using the placeholder ``${secret:NAME}``;
:func:`care.core.config.load_config` resolves placeholders
once at load time so providers see the real value without ever
having it written into the main YAML.

Design notes:

- Two files instead of one. Operators that publish their config (to a
  config-management repo, a backup, a SBOM bundle) avoid leaking
  secrets by simply omitting the sidecar. The placeholder string in
  ``config.yaml`` is the entire visible footprint.

- Placeholder names are restricted to ``[A-Z0-9_]+``. The GUI never
  accepts user-supplied placeholder strings directly — the
  ``POST /api/config/secrets`` endpoint validates the name on entry.

- The endpoint is **write-only**. The list endpoint returns names
  only; nothing in the API surface ever round-trips a secret value.

- Threat model: secrets.yaml is now writable through the loopback
  API. That is the same trust boundary as ``config.yaml``. The
  change-review process (and ``docs/security.md`` §"What this
  software does NOT defend against") already names operator
  filesystem access as out of scope; the API write authority does
  not widen the boundary so long as the server stays bound to
  127.0.0.1.
"""
from __future__ import annotations

import logging
import os
import re
import threading
from pathlib import Path
from typing import Any, Optional

import yaml

_log = logging.getLogger(__name__)

SECRETS_FILENAME: str = "secrets.yaml"
"""Sibling filename for the secrets sidecar."""

_NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
"""Allowed secret-name shape: SCREAMING_SNAKE_CASE only."""

_PLACEHOLDER_RE = re.compile(r"\$\{secret:([A-Z][A-Z0-9_]*)\}")
"""Recogniser for ``${secret:NAME}`` placeholders in config values."""

_SECRETS_LOCK = threading.RLock()


def is_valid_secret_name(name: str) -> bool:
    return isinstance(name, str) and bool(_NAME_RE.match(name))


def resolve_secrets_path(config_path: Path) -> Path:
    """Return the conventional sibling path for ``config_path``."""
    return Path(config_path).parent / SECRETS_FILENAME


def _read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    raw = path.read_text(encoding="utf-8")
    try:
        data = yaml.safe_load(raw) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"{path} is not valid YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path} root is not a mapping")
    return data


def load_secrets(path: Path) -> dict[str, str]:
    """Return the ``{NAME: value}`` map from ``path`` (or empty)."""
    data = _read_yaml(path)
    secrets = data.get("secrets") or {}
    if not isinstance(secrets, dict):
        return {}
    out: dict[str, str] = {}
    for k, v in secrets.items():
        if isinstance(k, str) and isinstance(v, (str, int, float)):
            out[str(k)] = str(v)
    return out


def list_secret_names(path: Path) -> list[str]:
    return sorted(load_secrets(path).keys())


def _atomic_write(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    payload = {
        "_warning": "Do not commit this file. Generated by the GUI.",
        "secrets": data,
    }
    try:
        with tmp.open("w", encoding="utf-8") as fh:
            yaml.safe_dump(payload, fh, sort_keys=True, default_flow_style=False)
        os.replace(tmp, path)
    except Exception:
        try:
            tmp.unlink()
        except OSError:
            pass
        raise
    _try_chmod_user_only(path)


def _try_chmod_user_only(path: Path) -> None:
    """Restrict ``path`` to its owner.

    - **POSIX**: ``chmod 600``.
    - **Windows**: invoke ``icacls /inheritance:r /grant:r <user>:F``
      so the file inherits no broader permissions and only the
      current user can read/write. The OS already keeps inherited
      permissions on the parent dir, so without this step a freshly
      written ``secrets.yaml`` can be readable by anything that can
      enumerate ``%LOCALAPPDATA%``.

    Best-effort: failures don't bubble up. The file is local; if the
    permission change fails the process owner can still read it
    because they just wrote it. We log a warning so an air-gap audit
    can spot a host where ACLs aren't enforced.
    """
    if os.name == "posix":
        try:
            os.chmod(path, 0o600)
        except OSError as exc:
            _log.warning("chmod 600 on %s failed: %s", path, exc)
        return
    if os.name == "nt":
        _apply_windows_user_only_acl(path)


def _apply_windows_user_only_acl(path: Path) -> None:
    """Use icacls to mark ``path`` as user-only.

    Equivalent of POSIX ``chmod 600``. We use ``icacls`` rather than
    pywin32 to keep the secrets module dep-free.

    Sequence:
      1. ``/inheritance:r`` — drop inherited ACEs (else other users
         on the box may inherit Read from the parent).
      2. ``/grant:r %USERNAME%:F`` — replace any existing ACE for
         the current user with Full control.
    """
    import subprocess

    user = os.environ.get("USERNAME") or os.environ.get("USER") or ""
    if not user:
        _log.warning(
            "cannot derive current Windows username; skipping ACL on %s",
            path,
        )
        return
    try:
        subprocess.run(
            [
                "icacls",
                str(path),
                "/inheritance:r",
                "/grant:r",
                f"{user}:F",
            ],
            check=False,
            capture_output=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover
        _log.warning("icacls on %s failed: %s", path, exc)


def save_secret(path: Path, name: str, value: str) -> None:
    """Persist ``name=value`` to ``path``.

    Existing keys are overwritten; other keys are preserved.
    Validates the name shape — ill-formed names are rejected so a
    bad write can't sneak past the placeholder regex.
    """
    if not is_valid_secret_name(name):
        raise ValueError(
            f"secret name {name!r} must match {_NAME_RE.pattern}"
        )
    if not isinstance(value, str):
        raise ValueError("secret value must be a string")
    with _SECRETS_LOCK:
        existing = load_secrets(path)
        existing[name] = value
        _atomic_write(path, existing)


def delete_secret(path: Path, name: str) -> bool:
    """Remove ``name`` from ``path``. Returns True if anything changed."""
    if not is_valid_secret_name(name):
        return False
    with _SECRETS_LOCK:
        existing = load_secrets(path)
        if name not in existing:
            return False
        del existing[name]
        _atomic_write(path, existing)
        return True


def resolve_placeholders(value: Any, secrets: dict[str, str]) -> Any:
    """Recursively expand ``${secret:NAME}`` placeholders.

    - Strings: any ``${secret:NAME}`` substring whose ``NAME`` is
      present in ``secrets`` is replaced with the value. Unknown
      placeholders are left in place — the consuming provider will
      surface a clear error when it tries to use the unresolved
      string.
    - Dicts / lists / tuples: walked recursively.
    - Other types: returned unchanged.
    """
    if isinstance(value, str):
        return _PLACEHOLDER_RE.sub(
            lambda m: secrets.get(m.group(1), m.group(0)),
            value,
        )
    if isinstance(value, dict):
        return {k: resolve_placeholders(v, secrets) for k, v in value.items()}
    if isinstance(value, list):
        return [resolve_placeholders(v, secrets) for v in value]
    if isinstance(value, tuple):
        return tuple(resolve_placeholders(v, secrets) for v in value)
    return value


def derive_name_for_path(dotted_path: str) -> Optional[str]:
    """Convention: ``llm.providers.openai.api_key`` → ``OPENAI_API_KEY``.

    Returns ``None`` for paths that don't match the
    ``<section>.providers.<provider>.<field>`` shape used for
    per-provider credentials. The GUI uses this to suggest a name
    when the operator clicks "Set secret" on a provider field.
    """
    parts = dotted_path.split(".")
    if len(parts) < 4 or parts[1] != "providers":
        return None
    provider = parts[2]
    field = ".".join(parts[3:])
    candidate = f"{provider}_{field}".upper().replace(".", "_")
    return candidate if is_valid_secret_name(candidate) else None
